# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job name is mybuild
  mybuild:
    # Runner type that the job will run on
    runs-on: ubuntu-latest

  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    # omitted steps for brevity

  AppCenterDistibute:
    runs-on: ubuntu-latest
    needs: Android
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: my-artifact

    - name: App Center
      uses: wzieba/AppCenter-Github-Action@v1.0.0
      with:
        # App name followed by username
        appName: Ch-DemoOrg/demoapp
        # Upload token - you can get one from appcenter.ms/
          settings
        token: ${{ secrets.AppCenterAPIToken }}
        # Distribution group
        group: alphatesters
        # Artefact to upload (.apk or .ipa)
        file: AwesomeApp/AwesomeApp.Android/bin/Debug/com.
        companyname.AwesomeApp.apk
        # Release notes visible on release page
        releaseNotes: "demo test"
